#!/bin/bash -ex

generated_template="/tmp/liztoff.com-generated-cloudformation.yml"

aws cloudformation package \
        --template-file "cloudformation.yml" \
        --s3-bucket sam-915290536872 \
        --output-template-file "${generated_template}" \
        --use-json

code_uri="$(jq '.Resources.S3UploadLambda.Properties.CodeUri' "${generated_template}" --raw-output)"

aws cloudformation deploy \
        --template-file "${generated_template}" \
        --stack-name liztoff-com \
        --capabilities CAPABILITY_IAM \
        --parameter-overrides "DeploymentContentVersion=${code_uri}" \
        --no-fail-on-empty-changeset
