on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NVM Install
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          . $HOME/.nvm/nvm.sh
          nvm install
      - name: Full Build
        run: |
          npm ci
          npm run release
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_SECRET }}
        run: npm run deploy
  automerge:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2.0 
        with:
          github-token: ${{secrets.DEPENDABOT_PAT}}
